package com.mytool.springModel;


import java.math.BigDecimal;

/**
 * 春节营销活动记录
 *
 * @author duankd
 */
public class SpringFestivalCorp {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * temp_spring_festival_activities
     *
     * @mbg.generated Tue Jan 19 10:09:04 CST 2021
     */
    private static final long serialVersionUID = 1L;
    /**
     * 公司id(主键)
     */
    private Long corpId;

    /**
     * 上传次数
     */
    private Integer uploadNum;

    /**
     * 下载次数
     */
    private Integer downloadNum;

    /**
     * 上传下载总次数
     */
    private Integer uploadDownloadNum;

    /**
     * 上传下载总次数排名
     */
    private Integer uploadDownloadNo;
    /**
     * 上传下载总次数排名比例
     */
    private BigDecimal uploadDownloadRate;

    public Long getCorpId() {
        return corpId;
    }

    public void setCorpId(Long corpId) {
        this.corpId = corpId;
    }

    public Integer getUploadNum() {
        return uploadNum;
    }

    public void setUploadNum(Integer uploadNum) {
        this.uploadNum = uploadNum;
    }

    public Integer getDownloadNum() {
        return downloadNum;
    }

    public void setDownloadNum(Integer downloadNum) {
        this.downloadNum = downloadNum;
    }

    public Integer getUploadDownloadNum() {
        return uploadDownloadNum;
    }

    public void setUploadDownloadNum(Integer uploadDownloadNum) {
        this.uploadDownloadNum = uploadDownloadNum;
    }

    public Integer getUploadDownloadNo() {
        return uploadDownloadNo;
    }

    public void setUploadDownloadNo(Integer uploadDownloadNo) {
        this.uploadDownloadNo = uploadDownloadNo;
    }

    public BigDecimal getUploadDownloadRate() {
        return uploadDownloadRate;
    }

    public void setUploadDownloadRate(BigDecimal uploadDownloadRate) {
        this.uploadDownloadRate = uploadDownloadRate;
    }

    @Override
    public String toString() {
        return "SpringFestivalCorp{" +
                "corpId=" + corpId +
                ", uploadNum=" + uploadNum +
                ", downloadNum=" + downloadNum +
                ", uploadDownloadNum=" + uploadDownloadNum +
                ", uploadDownloadNo=" + uploadDownloadNo +
                ", uploadDownloadRate=" + uploadDownloadRate +
                '}';
    }
}