package com.mytool.springModel;


import java.math.BigDecimal;
import java.util.Date;

/**
 * 春节营销活动记录
 *
 * @author duankd
 */
public class SpringFestivalRecord {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * temp_spring_festival_activities
     *
     * @mbg.generated Tue Jan 19 10:09:04 CST 2021
     */
    private static final long serialVersionUID = 1L;
    /**
     * 用户ID(主键)
     */
    private Long userId;
    /**
     * 第一个公司id
     */
    private Long firstCorpId;
    /**
     * 第一次加入企业时间
     */
    private Date createTime;
    /**
     * 加入排名
     */
    private Integer joinNo;
    /**
     * 加入排名比例
     */
    private BigDecimal joinRate;
    /**
     * 登陆次数
     */
    private Integer loginNum;
    /**
     * 登陆排名
     */
    private Integer loginNo;
    /**
     * 登陆排名比例
     */
    private BigDecimal loginRate;

    /**
     * 分享次数
     */
    private Integer shareNum;
    /**
     * 邀请次数
     */
    private Integer inviteNum;
    /**
     * 邀请较多的用户ids
     */
    private String inviteUserIds;
    /**
     * 工作时间段 1、早上6-12，2、中午12-21，3、晚上21-6
     */
    private Integer maxWorkingTimeWindow;

    /**
     * 上传次数
     */
    private Integer uploadNum;

    /**
     * 下载次数
     */
    private Integer downloadNum;

    /**
     * 上传下载总次数
     */
    private Integer uploadDownloadNum;

    /**
     * 上传下载总次数排名
     */
    private Integer uploadDownloadNo;
    /**
     * 上传下载总次数排名比例
     */
    private BigDecimal uploadDownloadRate;
    /**
     * 是否是管理员或者代管理员（角色id=1、4）
     */
    private Long adminFlag;

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getFirstCorpId() {
        return firstCorpId;
    }

    public void setFirstCorpId(Long firstCorpId) {
        this.firstCorpId = firstCorpId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Integer getJoinNo() {
        return joinNo;
    }

    public void setJoinNo(Integer joinNo) {
        this.joinNo = joinNo;
    }

    public BigDecimal getJoinRate() {
        return joinRate;
    }

    public void setJoinRate(BigDecimal joinRate) {
        this.joinRate = joinRate;
    }

    public Integer getLoginNum() {
        return loginNum;
    }

    public void setLoginNum(Integer loginNum) {
        this.loginNum = loginNum;
    }

    public Integer getLoginNo() {
        return loginNo;
    }

    public void setLoginNo(Integer loginNo) {
        this.loginNo = loginNo;
    }

    public BigDecimal getLoginRate() {
        return loginRate;
    }

    public void setLoginRate(BigDecimal loginRate) {
        this.loginRate = loginRate;
    }

    public Integer getShareNum() {
        return shareNum;
    }

    public void setShareNum(Integer shareNum) {
        this.shareNum = shareNum;
    }

    public Integer getInviteNum() {
        return inviteNum;
    }

    public void setInviteNum(Integer inviteNum) {
        this.inviteNum = inviteNum;
    }

    public String getInviteUserIds() {
        return inviteUserIds;
    }

    public void setInviteUserIds(String inviteUserIds) {
        this.inviteUserIds = inviteUserIds;
    }

    public Integer getMaxWorkingTimeWindow() {
        return maxWorkingTimeWindow;
    }

    public void setMaxWorkingTimeWindow(Integer maxWorkingTimeWindow) {
        this.maxWorkingTimeWindow = maxWorkingTimeWindow;
    }

    public Integer getUploadNum() {
        return uploadNum;
    }

    public void setUploadNum(Integer uploadNum) {
        this.uploadNum = uploadNum;
    }

    public Integer getDownloadNum() {
        return downloadNum;
    }

    public void setDownloadNum(Integer downloadNum) {
        this.downloadNum = downloadNum;
    }

    public Integer getUploadDownloadNum() {
        return uploadDownloadNum;
    }

    public void setUploadDownloadNum(Integer uploadDownloadNum) {
        this.uploadDownloadNum = uploadDownloadNum;
    }

    public Integer getUploadDownloadNo() {
        return uploadDownloadNo;
    }

    public void setUploadDownloadNo(Integer uploadDownloadNo) {
        this.uploadDownloadNo = uploadDownloadNo;
    }

    public BigDecimal getUploadDownloadRate() {
        return uploadDownloadRate;
    }

    public void setUploadDownloadRate(BigDecimal uploadDownloadRate) {
        this.uploadDownloadRate = uploadDownloadRate;
    }

    public Long getAdminFlag() {
        return adminFlag;
    }

    public void setAdminFlag(Long adminFlag) {
        this.adminFlag = adminFlag;
    }

    @Override
    public String toString() {
        return "SpringFestivalRecord{" +
                "userId=" + userId +
                ", firstCorpId=" + firstCorpId +
                ", createTime=" + createTime +
                ", joinNo=" + joinNo +
                ", joinRate=" + joinRate +
                ", loginNum=" + loginNum +
                ", loginNo=" + loginNo +
                ", loginRate=" + loginRate +
                ", shareNum=" + shareNum +
                ", inviteNum=" + inviteNum +
                ", inviteUserIds='" + inviteUserIds + '\'' +
                ", maxWorkingTimeWindow=" + maxWorkingTimeWindow +
                ", uploadNum=" + uploadNum +
                ", downloadNum=" + downloadNum +
                ", uploadDownloadNum=" + uploadDownloadNum +
                ", uploadDownloadNo=" + uploadDownloadNo +
                ", uploadDownloadRate=" + uploadDownloadRate +
                ", adminFlag=" + adminFlag +
                '}';
    }
}