package com.mytool.springModel;


import com.alibaba.fastjson.annotation.JSONField;

/**
 * 春节营销活动邀请用户记录
 *
 * @author duankd
 */
public class SpringFestivalInviteUserVO {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * temp_spring_festival_activities
     *
     * @mbg.generated Tue Jan 19 10:09:04 CST 2021
     */
    private static final long serialVersionUID = 1L;
    /**
     * 用户ID(主键)
     */
    @JSONField(serialize = false)
    private Long inviteUserId;
    /**
     * 用户名
     */
    private String inviteUserName;
    /**
     * 邀请次数
     */
    private Integer inviteUserNum;

    public SpringFestivalInviteUserVO() {
    }

    public Long getInviteUserId() {
        return inviteUserId;
    }

    public void setInviteUserId(Long inviteUserId) {
        this.inviteUserId = inviteUserId;
    }

    public String getInviteUserName() {
        return inviteUserName;
    }

    public void setInviteUserName(String inviteUserName) {
        this.inviteUserName = inviteUserName;
    }

    public Integer getInviteUserNum() {
        return inviteUserNum;
    }

    public void setInviteUserNum(Integer inviteUserNum) {
        this.inviteUserNum = inviteUserNum;
    }

    public Integer addInviteUserNum() {
        this.inviteUserNum += 1;
        return inviteUserNum;
    }

    @Override
    public String toString() {
        return "SpringFestivalInviteUserVO{" +
                "inviteUserId=" + inviteUserId +
                ", inviteUserName='" + inviteUserName + '\'' +
                ", inviteUserNum=" + inviteUserNum +
                '}';
    }
}