package com.mytool.springModel;


import com.alibaba.fastjson.annotation.JSONField;

/**
 * 春节营销活动记录
 *
 * @author duankd
 */
public class SpringFestivalFileInviteVO {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * temp_spring_festival_activities
     *
     * @mbg.generated Tue Jan 19 10:09:04 CST 2021
     */
    private static final long serialVersionUID = 1L;
    /**
     * 用户ID(主键)
     */
    @JSONField(name = "id")
    private Long userId;
    /**
     * 邀请类型 只用1
     */
    private Integer type;
    /**
     * 邀请的用户Name
     */
    private String name;

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "SpringFestivalFileInviteVO{" +
                "userId=" + userId +
                ", type=" + type +
                ", name='" + name + '\'' +
                '}';
    }
}