package com.mytool.springModel;


/**
 * 春节营销数据接收对象  user_id,corp_id,login_num,share_num,invite_num,max_working_time_window,upload_num,download_num,company_flag
 *
 * @author duankd
 */
public class SpringFestivalDataVO {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * temp_spring_festival_activities
     *
     * @mbg.generated Tue Jan 19 10:09:04 CST 2021
     */
    private static final long serialVersionUID = 1L;
    /**
     * 用户ID(主键)
     */
    private String userId;
    /**
     * 第一个公司id
     */
    private String corpId;
    /**
     * 登陆次数
     */
    private String loginNum;

    /**
     * 分享次数
     */
    private String shareNum;
    /**
     * 邀请次数
     */
    private String inviteNum;
    /**
     * 工作时间段 1、早上6-12，2、中午12-21，3、晚上21-6
     */
    private String maxWorkingTimeWindow;

    /**
     * 上传次数
     */
    private String uploadNum;

    /**
     * 下载次数
     */
    private String downloadNum;

    /**
     * 是否是管理员或者代管理员（角色id=1、4）
     */
    private String companyFlag;


    /**
     * @return
     */
    public boolean isCompanyFlag() {
        int flag = Integer.valueOf(this.companyFlag);
        if (flag == 0) {
            return false;
        } else {
            return true;
        }
    }

    /**
     * user_id,corp_id,login_num,share_num,invite_num,max_working_time_window,upload_num,download_num,company_flag
     *
     * @return
     */
    public SpringFestivalRecord transformToRecord() {
        if (!isCompanyFlag()) {
            SpringFestivalRecord record = new SpringFestivalRecord();
            record.setUserId(Long.valueOf(this.userId));
            record.setLoginNum(Integer.valueOf(this.loginNum));
            record.setShareNum(Integer.valueOf(this.shareNum));
            record.setInviteNum(Integer.valueOf(this.inviteNum));
            record.setMaxWorkingTimeWindow(Integer.valueOf(this.maxWorkingTimeWindow));
            record.setUploadNum(Integer.valueOf(this.uploadNum));
            record.setDownloadNum(Integer.valueOf(this.downloadNum));
            record.setUploadDownloadNum(record.getUploadNum() + record.getDownloadNum());
            return record;
        } else {
            return null;
        }
    }

    /**
     * user_id,corp_id,login_num,share_num,invite_num,max_working_time_window,upload_num,download_num,company_flag
     *
     * @return
     */
    public SpringFestivalCorp transformToCorp() {
        SpringFestivalCorp corp = new SpringFestivalCorp();
        if (isCompanyFlag()) {
            corp.setCorpId(Long.valueOf(this.corpId));
            corp.setUploadNum(Integer.valueOf(this.uploadNum));
            corp.setDownloadNum(Integer.valueOf(this.downloadNum));
            corp.setUploadDownloadNum(corp.getUploadNum() + corp.getDownloadNum());
            return corp;
        } else {
            return null;
        }
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getCorpId() {
        return corpId;
    }

    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }

    public String getLoginNum() {
        return loginNum;
    }

    public void setLoginNum(String loginNum) {
        this.loginNum = loginNum;
    }

    public String getShareNum() {
        return shareNum;
    }

    public void setShareNum(String shareNum) {
        this.shareNum = shareNum;
    }

    public String getInviteNum() {
        return inviteNum;
    }

    public void setInviteNum(String inviteNum) {
        this.inviteNum = inviteNum;
    }

    public String getMaxWorkingTimeWindow() {
        return maxWorkingTimeWindow;
    }

    public void setMaxWorkingTimeWindow(String maxWorkingTimeWindow) {
        this.maxWorkingTimeWindow = maxWorkingTimeWindow;
    }

    public String getUploadNum() {
        return uploadNum;
    }

    public void setUploadNum(String uploadNum) {
        this.uploadNum = uploadNum;
    }

    public String getDownloadNum() {
        return downloadNum;
    }

    public void setDownloadNum(String downloadNum) {
        this.downloadNum = downloadNum;
    }

    public String getCompanyFlag() {
        return companyFlag;
    }

    public void setCompanyFlag(String companyFlag) {
        this.companyFlag = companyFlag;
    }
}